# Generated by Django 5.2.1 on 2025-06-08 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_remove_car_photos_car_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='photo',
            new_name='photos',
        ),
    ]
