# Generated by Django 5.2.1 on 2025-06-08 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_rename_photo_car_photos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='photos',
            new_name='photo',
        ),
    ]
